# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

facebook_app_id: "308376989588423"
facebook_app_secret: "d5f02838d7147618c18b19db601b714e"

S3_BUCKET_NAME: "wm-petshuggy-test"
AWS_ACCESS_KEY_ID: "AKIAJ6RFRAZPRCVKZNTQ"
AWS_SECRET_ACCESS_KEY: "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"
AWS_REGION: "ap-northeast-1"
